services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr.gustau.cat
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /docker/sonarr:/config
      - /data/tv:/tv
      - /data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
