services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: ddns.gustau.cat
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /docker/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
