services:
  adguard:
    image: adguard/adguardhome
    container_name: dns.gustau.cat
    volumes:
      - /docker/adguard/work:/opt/adguardhome/work
      - /docker/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53
      - 53:53/udp
      - 3000:3000
      - 784:784/udp
      - 853:853
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443
      - 5443:5443/udp
