services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin.gustau.cat
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /docker/jellyfin/config:/config
      - /docker/jellyfin/cache:/cache
      - type: bind
        source: /data/tv
        target: /tv
      - type: bind
        source: /data/movies
        target: /movies
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.gustau.cat
    # Optional - may be necessary for docker healthcheck to pass
    # if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # hardware acceleration needs dri access
    devices:
      - /dev/dri:/dev/dri
