services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Rome
      - TRANSMISSION_WEB_HOME=transmission.gustau.cat
      - USER=transmission
      - PASS=transmission
      - WHITELIST=127.0.0.1,10.1.3.101
      - PEERPORT=51413
      - BLOCKLIST_ENABLED=true
      - BLOCKLIST_URL=https://mirror.codebucket.de/transmission/blocklist.p2p.gz
    volumes:
      - /docker/transmission/config:/config
      - /data/downloads:/downloads
      - /data/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
